pub mod block_device;
pub mod buffer;
pub mod buffer_pool;
pub mod capabilities;
pub mod error;
pub mod extent;
pub mod geometry;
pub mod memory;
pub mod range;
pub mod raw;
pub mod virtual_disk;

pub use block_device::BlockDevice;
pub use buffer::AlignedBuffer;
pub use buffer_pool::{BufferGuard, BufferPool};
pub use capabilities::Capabilities;
pub use error::{Error, Result};
pub use extent::{Extent, ExtentKind};
pub use geometry::DiskGeometry;
pub use memory::MemoryBlockDevice;
pub use range::DiskRange;
pub use raw::RawDisk;
pub use virtual_disk::VirtualDisk;
