[package]
name = "rvvdk-datamover"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rvvdk-core = { path = "../rvvdk-core" }
[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7.15"

[dev-dependencies]
rvvdk-local = { path = "../rvvdk-local" }
criterion = "0.8.2"

[[bench]]
name = "copy"
harness = false

[[bench]]
name = "buffer_pool"
harness = false

[[bench]]
name = "direct_io"
harness = false

[[bench]]
name = "io_uring"
harness = false

[[bench]]
name = "io_uring_direct"
harness = false