//! Linux private job journal. Records are not remote lease capabilities.
//!
//! Requires a caller-controlled local directory and trusted ancestors. Other
//! processes must cooperate with its advisory lock. Same-UID malicious writers,
//! hostile filesystems and offline rollback of the whole store are not excluded.
//! No network actions, automatic resume, recursive deletion or Drop cleanup.
use crate::contract::{ArtifactId, SourceSelection};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    ffi::CString,
    fmt,
    fs::{File, OpenOptions},
    io::{Read, Write},
    os::{
        fd::{AsRawFd, FromRawFd},
        unix::fs::{MetadataExt, OpenOptionsExt},
    },
    path::Path,
};

const MAX_RECORD: u64 = 8192;
const MEMBERS: [&str; 3] = ["disk-1.vmdk", "manifest.json", "owner"];
type Result<T> = std::result::Result<T, OwnershipError>;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, thiserror::Error)]
#[serde(rename_all = "snake_case")]
pub enum OwnershipError {
    #[error("job store is busy")]
    Busy,
    #[error("private job store or resource identity does not match")]
    Identity,
    #[error("job or transaction already exists")]
    Exists,
    #[error("invalid or corrupt job record")]
    Record,
    #[error("job transition is not permitted")]
    Transition,
    #[error("job persistence outcome is uncertain; reopen and reconcile")]
    Uncertain,
    #[error("local job I/O failed")]
    Io,
}

/// Generated by the store. A copied ID is not an authorization capability.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct OperationId([u8; 16]);
impl fmt::Debug for OperationId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("OperationId([redacted])")
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobState {
    Prepared,
    StageIntent,
    Staged,
    AcquireIntent,
    LeaseHeld,
    TransferComplete,
    CompleteIntent,
    CompletedLease,
    AbortIntent,
    AbortedLease,
    PublishIntent,
    Published,
    CleanupIntent,
    Cleaned,
}

/// An assessment, never permission to resume, abort, publish or remove a path.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RecoveryAction {
    NoResourcesRecorded,
    LocalPreparationUnknown,
    CheckOwnedLocalResources,
    RemoteOutcomeUnknown,
    PublicationUnknown,
    ValidatePublishedArtifact,
    CleanupMayBePartial,
    Terminal,
}
#[derive(Debug, Serialize)]
pub struct RecoveryReport {
    #[serde(skip)]
    pub operation: OperationId,
    pub state: JobState,
    pub sequence: u64,
    pub action: RecoveryAction,
    /// A surviving transaction blocks further mutation. It is never replayed.
    pub pending_transaction: bool,
}

#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Identity {
    dev: u64,
    ino: u64,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Stage {
    directory: Identity,
    members: [Identity; 3],
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Record {
    version: u32,
    store: Identity,
    artifact: [u8; 16],
    operation: [u8; 16],
    source: [u8; 32],
    sequence: u64,
    state: JobState,
    stage: Option<Stage>,
    lease_fingerprint: Option<[u8; 32]>,
}
#[derive(Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
struct Envelope {
    record: Record,
    sha256: [u8; 32],
}

/// Holds an exclusive nonblocking flock on the directory inode for its lifetime.
pub struct JobStore {
    directory: File,
    identity: Identity,
    poisoned: bool,
}
impl fmt::Debug for JobStore {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("JobStore([private])")
    }
}
impl Drop for JobStore {
    fn drop(&mut self) {
        // Explicit release avoids a fork/exec child's transient inherited file
        // description extending the lock beyond this owner's lifetime.
        // SAFETY: live directory descriptor; no pointer arguments.
        unsafe { libc::flock(self.directory.as_raw_fd(), libc::LOCK_UN) };
    }
}
/// Only created for a fresh operation. Reopening returns a RecoveryReport, not Job.
pub struct Job<'a> {
    store: &'a mut JobStore,
    record: Record,
    stage: Option<File>,
}
impl fmt::Debug for Job<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("Job([private])")
    }
}

impl JobStore {
    pub fn open(path: &Path) -> Result<Self> {
        let directory = OpenOptions::new()
            .read(true)
            .custom_flags(libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC)
            .open(path)
            .map_err(|_| OwnershipError::Io)?;
        private(&directory, true)?;
        // SAFETY: a live descriptor; flock has no pointer arguments.
        if unsafe { libc::flock(directory.as_raw_fd(), libc::LOCK_EX | libc::LOCK_NB) } != 0 {
            return Err(
                if std::io::Error::last_os_error().raw_os_error() == Some(libc::EWOULDBLOCK) {
                    OwnershipError::Busy
                } else {
                    OwnershipError::Io
                },
            );
        }
        let identity = identity(&directory)?;
        Ok(Self {
            directory,
            identity,
            poisoned: false,
        })
    }
    pub fn create(&mut self, artifact: ArtifactId, source: &SourceSelection) -> Result<Job<'_>> {
        self.ready()?;
        let mut record = Record {
            version: 1,
            store: self.identity,
            artifact: *artifact.as_bytes(),
            operation: [0; 16],
            source: source.ownership_binding(),
            sequence: 0,
            state: JobState::Prepared,
            stage: None,
            lease_fingerprint: None,
        };
        if exists(&self.directory, &record_name(&record.artifact))?
            || exists(&self.directory, &transaction_name(&record.artifact))?
        {
            return Err(OwnershipError::Exists);
        }
        random(&mut record.operation)?;
        self.commit(&record, true)?;
        Ok(Job {
            store: self,
            record,
            stage: None,
        })
    }
    pub fn recover(
        &self,
        artifact: ArtifactId,
        source: &SourceSelection,
    ) -> Result<RecoveryReport> {
        let r = self.read(artifact, source)?;
        Ok(RecoveryReport {
            operation: OperationId(r.operation),
            state: r.state,
            sequence: r.sequence,
            action: match r.state {
                JobState::Prepared => RecoveryAction::NoResourcesRecorded,
                JobState::StageIntent => RecoveryAction::LocalPreparationUnknown,
                JobState::Staged | JobState::CompletedLease | JobState::AbortedLease => {
                    RecoveryAction::CheckOwnedLocalResources
                }
                JobState::AcquireIntent
                | JobState::LeaseHeld
                | JobState::TransferComplete
                | JobState::CompleteIntent
                | JobState::AbortIntent => RecoveryAction::RemoteOutcomeUnknown,
                JobState::PublishIntent => RecoveryAction::PublicationUnknown,
                JobState::Published => RecoveryAction::ValidatePublishedArtifact,
                JobState::CleanupIntent => RecoveryAction::CleanupMayBePartial,
                JobState::Cleaned => RecoveryAction::Terminal,
            },
            pending_transaction: exists(&self.directory, &transaction_name(&r.artifact))?,
        })
    }
    /// Explicit cleanup of only this private store's stamped resources. It is
    /// unavailable for uncertain remote/publication states or pending transactions.
    pub fn cleanup_local(
        &mut self,
        artifact: ArtifactId,
        operation: OperationId,
        source: &SourceSelection,
    ) -> Result<()> {
        let result = self.cleanup_inner(artifact, operation, source);
        if matches!(result, Err(OwnershipError::Io | OwnershipError::Uncertain)) {
            self.poisoned = true;
        }
        result
    }
    fn cleanup_inner(
        &mut self,
        artifact: ArtifactId,
        operation: OperationId,
        source: &SourceSelection,
    ) -> Result<()> {
        self.ready()?;
        let mut r = self.read(artifact, source)?;
        if r.operation != operation.0 {
            return Err(OwnershipError::Identity);
        }
        if exists(&self.directory, &transaction_name(&r.artifact))? {
            return Err(OwnershipError::Uncertain);
        }
        if r.state == JobState::Cleaned {
            return Ok(());
        }
        if !matches!(
            r.state,
            JobState::Staged
                | JobState::CompletedLease
                | JobState::AbortedLease
                | JobState::CleanupIntent
        ) {
            return Err(OwnershipError::Transition);
        }
        let partial = r.state == JobState::CleanupIntent;
        let directory = self.check_stage(&r, partial)?;
        if !partial {
            self.advance(&mut r, JobState::CleanupIntent)?;
        }
        if let Some(directory) = directory {
            let stamp = r.stage.as_ref().ok_or(OwnershipError::Record)?;
            for (i, name) in MEMBERS.iter().enumerate() {
                check_named(
                    &self.directory,
                    &stage_name(&r.operation),
                    stamp.directory,
                    true,
                )?;
                if exists(&directory, name)? {
                    check_named(&directory, name, stamp.members[i], false)?;
                    unlink(&directory, name, false)?;
                    checkpoint(match i {
                        0 => "cleanup_payload",
                        1 => "cleanup_manifest",
                        _ => "cleanup_owner",
                    })?;
                }
            }
            directory.sync_all().map_err(|_| OwnershipError::Io)?;
            check_named(
                &self.directory,
                &stage_name(&r.operation),
                stamp.directory,
                true,
            )?;
            // ENOTEMPTY preserves unknown files; never recurse or delete them.
            unlink(&self.directory, &stage_name(&r.operation), true)?;
            checkpoint("cleanup_directory")?;
            self.directory
                .sync_all()
                .map_err(|_| OwnershipError::Uncertain)?;
        }
        self.advance(&mut r, JobState::Cleaned)
    }
    fn ready(&self) -> Result<()> {
        if self.poisoned {
            return Err(OwnershipError::Uncertain);
        }
        private(&self.directory, true)
    }
    fn read(&self, id: ArtifactId, source: &SourceSelection) -> Result<Record> {
        let mut file = open_at(
            &self.directory,
            &record_name(id.as_bytes()),
            false,
            false,
            false,
        )?;
        private(&file, false)?;
        let bytes = bounded_read(&mut file, MAX_RECORD)?;
        let envelope: Envelope =
            serde_json::from_slice(&bytes).map_err(|_| OwnershipError::Record)?;
        let r = envelope.record;
        let encoded = serde_json::to_vec(&r).map_err(|_| OwnershipError::Record)?;
        if envelope.sha256 != <[u8; 32]>::from(Sha256::digest(&encoded))
            || r.version != 1
            || r.operation == [0; 16]
            || r.artifact != *id.as_bytes()
            || r.store != self.identity
            || r.source != source.ownership_binding()
            || !valid_sequence(r.state, r.sequence)
        {
            return Err(OwnershipError::Record);
        }
        if let Some(stage) = &r.stage
            && (stage.directory.dev != r.store.dev
                || stage.directory.ino == 0
                || stage
                    .members
                    .iter()
                    .any(|m| m.dev != stage.directory.dev || m.ino == 0))
        {
            return Err(OwnershipError::Record);
        }
        let has_stage = !matches!(r.state, JobState::Prepared | JobState::StageIntent);
        let has_lease = matches!(
            r.state,
            JobState::LeaseHeld
                | JobState::TransferComplete
                | JobState::CompleteIntent
                | JobState::CompletedLease
                | JobState::AbortIntent
                | JobState::AbortedLease
                | JobState::PublishIntent
                | JobState::Published
        );
        if has_stage != r.stage.is_some()
            || (has_lease && r.lease_fingerprint.is_none())
            || (matches!(
                r.state,
                JobState::Prepared
                    | JobState::StageIntent
                    | JobState::Staged
                    | JobState::AcquireIntent
            ) && r.lease_fingerprint.is_some())
        {
            return Err(OwnershipError::Record);
        }
        if matches!(r.state, JobState::CleanupIntent | JobState::Cleaned)
            && r.lease_fingerprint.is_some() != (r.sequence >= 7)
        {
            return Err(OwnershipError::Record);
        }
        Ok(r)
    }
    fn check_stage(&self, r: &Record, partial: bool) -> Result<Option<File>> {
        let name = stage_name(&r.operation);
        if !exists(&self.directory, &name)? {
            return if partial {
                Ok(None)
            } else {
                Err(OwnershipError::Identity)
            };
        }
        let stamp = r.stage.as_ref().ok_or(OwnershipError::Record)?;
        let dir = check_named(&self.directory, &name, stamp.directory, true)?;
        for (i, member) in MEMBERS.iter().enumerate() {
            if partial && !exists(&dir, member)? {
                continue;
            }
            let mut file = check_named(&dir, member, stamp.members[i], false)?;
            if *member == "owner" && bounded_read(&mut file, 16)? != r.operation {
                return Err(OwnershipError::Identity);
            }
        }
        Ok(Some(dir))
    }
    fn advance(&mut self, r: &mut Record, state: JobState) -> Result<()> {
        self.ready()?;
        if !allowed(r.state, state) {
            return Err(OwnershipError::Transition);
        }
        let mut next = r.clone();
        next.sequence = next.sequence.checked_add(1).ok_or(OwnershipError::Record)?;
        if next.sequence > 32 {
            return Err(OwnershipError::Record);
        }
        next.state = state;
        self.commit(&next, false)?;
        *r = next;
        Ok(())
    }
    fn commit(&mut self, record: &Record, initial: bool) -> Result<()> {
        self.ready()?;
        let result = (|| {
            let name = record_name(&record.artifact);
            let temp = transaction_name(&record.artifact);
            if !initial {
                private(
                    &open_at(&self.directory, &name, false, false, false)?,
                    false,
                )?;
            }
            let data = serde_json::to_vec(record).map_err(|_| OwnershipError::Record)?;
            let envelope = Envelope {
                record: record.clone(),
                sha256: Sha256::digest(data).into(),
            };
            let data = serde_json::to_vec(&envelope).map_err(|_| OwnershipError::Record)?;
            if data.len() as u64 > MAX_RECORD {
                return Err(OwnershipError::Record);
            }
            let mut file = open_at(&self.directory, &temp, true, true, false)?;
            // Separate writes allow the real partial-write crash case to be tested.
            let middle = data.len() / 2;
            file.write_all(&data[..middle])
                .map_err(|_| OwnershipError::Io)?;
            checkpoint("record_partial")?;
            file.write_all(&data[middle..])
                .map_err(|_| OwnershipError::Io)?;
            checkpoint("record_written")?;
            file.sync_all().map_err(|_| OwnershipError::Io)?;
            checkpoint("record_synced")?;
            let from = cstr(&temp)?;
            let to = cstr(&name)?;
            // SAFETY: pinned directory and fixed generated single-component names.
            if unsafe {
                libc::renameat2(
                    self.directory.as_raw_fd(),
                    from.as_ptr(),
                    self.directory.as_raw_fd(),
                    to.as_ptr(),
                    if initial { libc::RENAME_NOREPLACE } else { 0 },
                )
            } != 0
            {
                return Err(OwnershipError::Io);
            }
            checkpoint("record_renamed")?;
            self.directory.sync_all().map_err(|_| OwnershipError::Io)?;
            checkpoint("record_durable")?;
            Ok(())
        })();
        if result.is_err() {
            self.poisoned = true;
            return Err(OwnershipError::Uncertain);
        }
        Ok(())
    }
}

impl Job<'_> {
    pub fn operation(&self) -> OperationId {
        OperationId(self.record.operation)
    }
    pub fn state(&self) -> JobState {
        self.record.state
    }
    /// Create the fixed owned members and marker. A failed preparation is never
    /// retried or automatically cleaned using only its generated directory name.
    pub fn prepare_stage(&mut self) -> Result<()> {
        self.store
            .advance(&mut self.record, JobState::StageIntent)?;
        let name = stage_name(&self.record.operation);
        let raw = cstr(&name)?;
        // SAFETY: pinned directory and generated single component.
        if unsafe { libc::mkdirat(self.store.directory.as_raw_fd(), raw.as_ptr(), 0o700) } != 0 {
            return Err(OwnershipError::Io);
        }
        checkpoint("stage_created")?;
        let directory = open_at(&self.store.directory, &name, false, false, true)?;
        private(&directory, true)?;
        let mut members = [Identity { dev: 0, ino: 0 }; 3];
        for (i, member) in MEMBERS.iter().enumerate() {
            let mut file = open_at(&directory, member, true, true, false)?;
            if *member == "owner" {
                file.write_all(&self.record.operation)
                    .map_err(|_| OwnershipError::Io)?;
            }
            file.sync_all().map_err(|_| OwnershipError::Io)?;
            members[i] = identity(&file)?;
        }
        directory.sync_all().map_err(|_| OwnershipError::Io)?;
        self.store
            .directory
            .sync_all()
            .map_err(|_| OwnershipError::Io)?;
        checkpoint("stage_durable")?;
        self.record.stage = Some(Stage {
            directory: identity(&directory)?,
            members,
        });
        self.store.advance(&mut self.record, JobState::Staged)?;
        self.stage = Some(directory);
        Ok(())
    }
    /// Caller writes through the pinned, newly created member. No path from a
    /// manifest is used. Content verification/durability belongs to R6.1c.
    pub fn payload_file(&self) -> Result<File> {
        self.member(0)
    }
    pub fn metadata_file(&self) -> Result<File> {
        self.member(1)
    }
    fn member(&self, index: usize) -> Result<File> {
        self.store.ready()?;
        if !matches!(
            self.record.state,
            JobState::Staged
                | JobState::AcquireIntent
                | JobState::LeaseHeld
                | JobState::TransferComplete
        ) {
            return Err(OwnershipError::Transition);
        }
        let dir = self.stage.as_ref().ok_or(OwnershipError::Transition)?;
        let expected = self.record.stage.as_ref().ok_or(OwnershipError::Record)?;
        check_named(
            &self.store.directory,
            &stage_name(&self.record.operation),
            expected.directory,
            true,
        )?;
        let file = open_at(dir, MEMBERS[index], true, false, false)?;
        private(&file, false)?;
        if identity(&file)? != expected.members[index] {
            return Err(OwnershipError::Identity);
        }
        Ok(file)
    }
    pub fn begin_acquire(&mut self) -> Result<()> {
        self.store
            .advance(&mut self.record, JobState::AcquireIntent)
    }
    /// Record the current process's acknowledged lease, not a deserialized claim.
    /// The actual remote capability remains caller-owned and is never persisted.
    pub fn acknowledge_lease(&mut self, reference: &str) -> Result<()> {
        if reference.is_empty() || reference.len() > 256 || reference.chars().any(char::is_control)
        {
            return Err(OwnershipError::Record);
        }
        if self.record.state != JobState::AcquireIntent {
            return Err(OwnershipError::Transition);
        }
        self.record.lease_fingerprint = Some(Sha256::digest(reference.as_bytes()).into());
        self.store.advance(&mut self.record, JobState::LeaseHeld)
    }
    pub fn transfer_complete(&mut self) -> Result<()> {
        self.store
            .advance(&mut self.record, JobState::TransferComplete)
    }
    pub fn begin_complete(&mut self) -> Result<()> {
        self.store
            .advance(&mut self.record, JobState::CompleteIntent)
    }
    pub fn acknowledge_complete(&mut self) -> Result<()> {
        self.store
            .advance(&mut self.record, JobState::CompletedLease)
    }
    pub fn begin_abort(&mut self) -> Result<()> {
        self.store.advance(&mut self.record, JobState::AbortIntent)
    }
    pub fn acknowledge_abort(&mut self) -> Result<()> {
        self.store.advance(&mut self.record, JobState::AbortedLease)
    }
    pub fn begin_publish(&mut self) -> Result<()> {
        self.store
            .advance(&mut self.record, JobState::PublishIntent)
    }
    /// Records caller-observed durable publication; does not publish a directory.
    pub fn acknowledge_publish(&mut self) -> Result<()> {
        self.store.advance(&mut self.record, JobState::Published)
    }
}

fn allowed(from: JobState, to: JobState) -> bool {
    use JobState::*;
    matches!(
        (from, to),
        (Prepared, StageIntent)
            | (StageIntent, Staged)
            | (Staged, AcquireIntent)
            | (AcquireIntent, LeaseHeld)
            | (LeaseHeld, TransferComplete)
            | (TransferComplete, CompleteIntent)
            | (CompleteIntent, CompletedLease)
            | (LeaseHeld | TransferComplete, AbortIntent)
            | (AbortIntent, AbortedLease)
            | (CompletedLease, PublishIntent)
            | (PublishIntent, Published)
            | (Staged | CompletedLease | AbortedLease, CleanupIntent)
            | (CleanupIntent, Cleaned)
    )
}
fn valid_sequence(state: JobState, sequence: u64) -> bool {
    use JobState::*;
    match state {
        Prepared => sequence == 0,
        StageIntent => sequence == 1,
        Staged => sequence == 2,
        AcquireIntent => sequence == 3,
        LeaseHeld => sequence == 4,
        TransferComplete => sequence == 5,
        CompleteIntent => sequence == 6,
        CompletedLease => sequence == 7,
        AbortIntent => matches!(sequence, 5 | 6),
        AbortedLease => matches!(sequence, 6 | 7),
        PublishIntent => sequence == 8,
        Published => sequence == 9,
        CleanupIntent => matches!(sequence, 3 | 7 | 8),
        Cleaned => matches!(sequence, 4 | 8 | 9),
    }
}
fn cstr(s: &str) -> Result<CString> {
    CString::new(s).map_err(|_| OwnershipError::Record)
}
fn record_name(id: &[u8; 16]) -> String {
    format!("job-{}.json", crate::transport::hex_string(id))
}
fn transaction_name(id: &[u8; 16]) -> String {
    format!("txn-{}.json", crate::transport::hex_string(id))
}
fn stage_name(id: &[u8; 16]) -> String {
    format!("stage-{}", crate::transport::hex_string(id))
}
fn identity(file: &File) -> Result<Identity> {
    let m = file.metadata().map_err(|_| OwnershipError::Io)?;
    Ok(Identity {
        dev: m.dev(),
        ino: m.ino(),
    })
}
fn private(file: &File, directory: bool) -> Result<()> {
    let m = file.metadata().map_err(|_| OwnershipError::Io)?;
    // SAFETY: geteuid takes no pointers and has no preconditions.
    if m.uid() != unsafe { libc::geteuid() }
        || m.mode() & 0o077 != 0
        || (if directory {
            !m.is_dir()
        } else {
            !m.is_file() || m.nlink() != 1
        })
    {
        Err(OwnershipError::Identity)
    } else {
        Ok(())
    }
}
fn open_at(dir: &File, name: &str, writable: bool, create: bool, directory: bool) -> Result<File> {
    let name = cstr(name)?;
    let flags = libc::O_NOFOLLOW
        | libc::O_CLOEXEC
        | libc::O_NONBLOCK
        | if writable {
            libc::O_RDWR
        } else {
            libc::O_RDONLY
        }
        | if create {
            libc::O_CREAT | libc::O_EXCL
        } else {
            0
        }
        | if directory { libc::O_DIRECTORY } else { 0 };
    // SAFETY: live dir descriptor and internally generated fixed component.
    let fd = unsafe { libc::openat(dir.as_raw_fd(), name.as_ptr(), flags, 0o600) };
    if fd < 0 {
        return Err(OwnershipError::Io);
    }
    // SAFETY: successful open returns a uniquely owned descriptor.
    Ok(unsafe { File::from_raw_fd(fd) })
}
fn exists(dir: &File, name: &str) -> Result<bool> {
    let name = cstr(name)?;
    let mut stat = std::mem::MaybeUninit::<libc::stat>::uninit();
    // SAFETY: live fd, NUL name, valid output storage; no symlinks followed.
    if unsafe {
        libc::fstatat(
            dir.as_raw_fd(),
            name.as_ptr(),
            stat.as_mut_ptr(),
            libc::AT_SYMLINK_NOFOLLOW,
        )
    } == 0
    {
        return Ok(true);
    }
    if std::io::Error::last_os_error().raw_os_error() == Some(libc::ENOENT) {
        Ok(false)
    } else {
        Err(OwnershipError::Io)
    }
}
fn check_named(dir: &File, name: &str, expected: Identity, directory: bool) -> Result<File> {
    let file = open_at(dir, name, false, false, directory)?;
    private(&file, directory)?;
    if identity(&file)? != expected {
        return Err(OwnershipError::Identity);
    }
    Ok(file)
}
fn unlink(dir: &File, name: &str, directory: bool) -> Result<()> {
    let name = cstr(name)?;
    // SAFETY: pinned directory and internally generated single component.
    if unsafe {
        libc::unlinkat(
            dir.as_raw_fd(),
            name.as_ptr(),
            if directory { libc::AT_REMOVEDIR } else { 0 },
        )
    } != 0
    {
        return Err(OwnershipError::Io);
    }
    Ok(())
}
fn bounded_read(file: &mut File, max: u64) -> Result<Vec<u8>> {
    if file.metadata().map_err(|_| OwnershipError::Io)?.len() > max {
        return Err(OwnershipError::Record);
    }
    let mut bytes = Vec::new();
    file.take(max + 1)
        .read_to_end(&mut bytes)
        .map_err(|_| OwnershipError::Io)?;
    if bytes.len() as u64 > max {
        return Err(OwnershipError::Record);
    }
    Ok(bytes)
}
fn random(bytes: &mut [u8; 16]) -> Result<()> {
    let mut filled = 0;
    while filled < bytes.len() {
        // SAFETY: writable initialized slice; kernel writes at most remaining bytes.
        let count = unsafe {
            libc::getrandom(bytes[filled..].as_mut_ptr().cast(), bytes.len() - filled, 0)
        };
        if count < 0 && std::io::Error::last_os_error().raw_os_error() == Some(libc::EINTR) {
            continue;
        }
        if count <= 0 {
            return Err(OwnershipError::Io);
        }
        filled += count as usize;
    }
    if *bytes == [0; 16] {
        return Err(OwnershipError::Io);
    }
    Ok(())
}
fn checkpoint(_name: &str) -> Result<()> {
    #[cfg(test)]
    {
        if std::env::var("RVDDK_TEST_JOB_CRASH").as_deref() == Ok(_name) {
            std::process::exit(77);
        }
        if tests::FAIL_POINT.with(|v| v.get()) == Some(_name) {
            return Err(OwnershipError::Io);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests;
