[package]
name = "rvvdk-vmdk"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = "2"
rvvdk-core = { path = "../rvvdk-core" }

[target.'cfg(target_os = "linux")'.dependencies]
rvvdk-local = { path = "../rvvdk-local" }
libc = "0.2.189"

[dev-dependencies]
rvvdk-datamover = { path = "../rvvdk-datamover" }
criterion = "0.8.2"

[[bench]]
name = "descriptor"
harness = false

[[bench]]
name = "resolution"
harness = false

[[bench]]
name = "logical"
harness = false

[[bench]]
name = "padding"
harness = false

[[bench]]
name = "sparse_header"
harness = false

[[bench]]
name = "sparse_metadata"
harness = false

[[bench]]
name = "sparse_disk"
harness = false

[[bench]]
name = "sparse_scale"
harness = false
